### ISSUE TITLE
Generate transfer learning plots

### ISSUE THREAD

**Issue by tangtaogo** [lightonai/contrastive-embeddings-for-neural-architectures#1]
Hello, thanks for your excellent work!
I have some trouble when I try to _Generate transfer learning plots between two search spaces_.  The _make_contrastive_transfer_plots.py_ need path_EPDJM_a and path_EPDJM_b. But the time of  using gen_epdjms.py to get the EPDJM is to long. So can I get your EPDJM(cifar10, nats_ss) ?

**Comment by DanielHesslow** [comment]
Thanks for your interest!

I've uploaded the EPDJMs for both the nats_ss and the 201 search spaces here:
http://storage.cloud.google.com/contrastive_embeddings_for_neural_architectures

For ease of use I've uploaded both the version normalized by the principal singular value and the unprocessed version. For the transfer learning we observe better results with the normed embeddings.

**Comment by tangtaogo** [comment]
Thank you so much for providing the link！
